# Gmail example config

[SMTP]
host = 'smtp.gmail.com'
port = 587                                      # 465 would be the ssl port
# use either ssl or starttls, not both
ssl = false
starttls = true
timeout = 15                                    # optional

[AUTH]
user = 'firstname.lastname@gmail.com'
password = 'pAsSwOrD'                           # use https://myaccount.google.com/lesssecureapps

[ADDR]
from = 'firstname.lastname@gmail.com'
to = 'firstname.lastname+nvchecker@gmail.com'   # for Gmail recipient addresses, you can add a plus sign ('+') after the username and any combination of words or numbers
